<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: articles.proto

namespace Articles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>articles.DeleteResponse</code>
 */
class DeleteResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Articles::initOnce();
        parent::__construct();
    }

}

