<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: articles.proto

namespace Articles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>articles.ListRequest</code>
 */
class ListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated string ids = 1;</code>
     */
    private $ids;

    public function __construct() {
        \GPBMetadata\Articles::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated string ids = 1;</code>
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * <code>repeated string ids = 1;</code>
     */
    public function setIds(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ids = $var;
    }

}

