<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: articles.proto

namespace Articles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>articles.UpdateRequest</code>
 */
class UpdateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.articles.Article article = 1;</code>
     */
    private $article = null;

    public function __construct() {
        \GPBMetadata\Articles::initOnce();
        parent::__construct();
    }

    /**
     * <code>.articles.Article article = 1;</code>
     */
    public function getArticle()
    {
        return $this->article;
    }

    /**
     * <code>.articles.Article article = 1;</code>
     */
    public function setArticle(&$var)
    {
        GPBUtil::checkMessage($var, \Articles\Article::class);
        $this->article = $var;
    }

}

